apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
type: Opaque
stringData:
  JWT_SECRET: "superSecretJwtSigningKeyForProductionDeploymentsMustBeAtLeast32BytesLong123456"
  MONGODB_URI: "mongodb+srv://Swaleha:swala%401234@cluster0.4xjv7hm.mongodb.net/UserName?retryWrites=true&w=majority"
  REDIS_HOST: "redis-service"
  KAFKA_SERVERS: "kafka-service:9092"
